version: "3"
services:
  rucio:
    image: docker.io/rucio/rucio-dev
    ports:
      - "8443:443"
    volumes:
      - ../../../tools:/opt/rucio/tools:Z
      - ../../../bin:/opt/rucio/bin:Z
      - ../../../lib:/opt/rucio/lib:Z
    environment:
      - X509_USER_CERT=/opt/rucio/etc/usercert.pem
      - X509_USER_KEY=/opt/rucio/etc/userkey.pem
      - RDBMS=postgres14
  ruciodb:
    image: docker.io/postgres:14
    environment:
      - POSTGRES_USER=rucio
      - POSTGRES_DB=rucio
      - POSTGRES_PASSWORD=secret
    command: ["-c", "fsync=off","-c", "synchronous_commit=off","-c", "full_page_writes=off"]
    ports:
      - "5432:5432"
  graphite:
    image: docker.io/graphiteapp/graphite-statsd
    ports:
      - "8080:80"
  influxdb:
    image: docker.io/influxdb:latest
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=myusername
      - DOCKER_INFLUXDB_INIT_PASSWORD=passwordpasswordpassword
      - DOCKER_INFLUXDB_INIT_ORG=rucio
      - DOCKER_INFLUXDB_INIT_BUCKET=rucio
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
  elasticsearch:
    image: docker.io/elasticsearch:7.4.0
    environment:
      - discovery.type=single-node
  activemq:
    image: docker.io/webcenter/activemq:latest
    environment:
      - ACTIVEMQ_CONFIG_NAME=activemq
      - ACTIVEMQ_CONFIG_DEFAULTACCOUNT=false
      - ACTIVEMQ_USERS_fts=supersecret
      - ACTIVEMQ_GROUPS_writes=fts
      - ACTIVEMQ_USERS_receiver=supersecret
      - ACTIVEMQ_GROUPS_reads=receiver
      - ACTIVEMQ_CONFIG_SCHEDULERENABLED=true
      - ACTIVEMQ_USERS_hermes=supersecret
      - ACTIVEMQ_CONFIG_QUEUES_events=/queue/events'
    ports:
      - "8161:8161"
