services:
  rucio:
    image: docker.io/rucio/rucio-dev
    ports:
      - "8443:443"
      - "8080:80"
    volumes:
      - ../../../tools:/opt/rucio/tools:Z
      - ../../../bin:/opt/rucio/bin:Z
      - ../../../lib:/opt/rucio/lib:Z
    environment:
      - X509_USER_CERT=/opt/rucio/etc/usercert.pem
      - X509_USER_KEY=/opt/rucio/etc/userkey.pem
      - RDBMS=postgres14
    command: ["/monit-entrypoint.sh"]
  ruciodb:
    image: docker.io/postgres:14
    environment:
      - POSTGRES_USER=rucio
      - POSTGRES_DB=rucio
      - POSTGRES_PASSWORD=secret
    command: ["-c", "fsync=off","-c", "synchronous_commit=off","-c", "full_page_writes=off"]
    ports:
      - "5432:5432"
  graphite:
    image: docker.io/graphiteapp/graphite-statsd
    ports:
      - "8080:80"
  fts:
    image: docker.io/rucio/fts
  ftsdb:
    image: docker.io/mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER=fts
      - MYSQL_PASSWORD=fts
      - MYSQL_ROOT_PASSWORD=fts
      - MYSQL_DATABASE=fts
  xrd1:
    image: docker.io/rucio/xrootd
    environment:
      - XRDPORT=1094
    volumes:
      - ../../certs/hostcert_xrd1.pem:/tmp/xrdcert.pem:Z
      - ../../certs/hostcert_xrd1.key.pem:/tmp/xrdkey.pem:Z
  xrd2:
    image: docker.io/rucio/xrootd
    environment:
      - XRDPORT=1095
    volumes:
      - ../../certs/hostcert_xrd2.pem:/tmp/xrdcert.pem:Z
      - ../../certs/hostcert_xrd2.key.pem:/tmp/xrdkey.pem:Z
  xrd3:
    image: docker.io/rucio/xrootd
    environment:
      - XRDPORT=1096
    volumes:
      - ../../certs/hostcert_xrd3.pem:/tmp/xrdcert.pem:Z
      - ../../certs/hostcert_xrd3.key.pem:/tmp/xrdkey.pem:Z
  xrd4:
    image: docker.io/rucio/xrootd
    environment:
      - XRDPORT=1097
    volumes:
      - ../../certs/hostcert_xrd4.pem:/tmp/xrdcert.pem:Z
      - ../../certs/hostcert_xrd4.key.pem:/tmp/xrdkey.pem:Z
  minio:
    image: docker.io/minio/minio
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password
    volumes:
      - ../../certs/hostcert_minio.pem:/root/.minio/certs/public.crt:Z
      - ../../certs/hostcert_minio.key.pem:/root/.minio/certs/private.key:Z
    command: ["server", "/data"]
  ssh1:
    image: docker.io/rucio/ssh
    volumes:
      - ../../certs/ssh/ruciouser_sshkey.pub:/tmp/sshkey.pub:Z
  activemq:
    image: docker.io/webcenter/activemq:latest
    environment:
       - ACTIVEMQ_CONFIG_NAME=activemq
       - ACTIVEMQ_CONFIG_DEFAULTACCOUNT=false
       - ACTIVEMQ_USERS_fts=supersecret
       - ACTIVEMQ_USERS_hermes=supersecret
       - ACTIVEMQ_USERS_logstash=supersecret
       - ACTIVEMQ_USERS_receiver=supersecret
       - ACTIVEMQ_GROUPS_writes=hermes,fts
       - ACTIVEMQ_GROUPS_reads=logstash,receiver
       - ACTIVEMQ_CONFIG_SCHEDULERENABLED=true
    ports:
      - "8161:8161"
  elasticsearch:
    image: docker.io/elasticsearch:7.4.0
    environment:
      - discovery.type=single-node
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.3.2
    command: bash -c "logstash-plugin install logstash-input-stomp ; /usr/local/bin/docker-entrypoint"
    volumes:
      - ./pipeline.conf:/usr/share/logstash/pipeline/pipeline.conf:Z
  kibana:
    image: docker.io/kibana:7.4.0
    ports:
      - "5601:5601"
  grafana:
    image: docker.io/grafana/grafana:latest
    ports:
      - "3000:3000"
