name: End to End integration tests

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout rucio source
        with:
          path: rucio
      - name: Checkout rucio containers repository
        uses: actions/checkout@v2
        with:
          repository: rucio/containers
          path: containers
      - name: Build Images
        shell: bash
        run: |
          pwd
          ls -la
          sed -i "s/RUN git clone .*/COPY ..\/rucio \/tmp\/rucio/" $GITHUB_WORKSPACE/containers/dev/Dockerfile_py3
          cat $GITHUB_WORKSPACE/containers/dev/Dockerfile_py3
#          docker build -t rucio-dev -f $GITHUB_WORKSPACE/containers/Dockerfile_py3 $GITHUB_WORKSPACE/containers
#      - name: Start containers
#        run: docker-compose -f etc/docker/dev/docker-compose-integration-test.yml up -d
#      - name: Initialize tests
#        run: docker exec -t dev_rucio_1 tools/run_tests_docker.sh -ir
#      - name: File Upload/Download Test
#        run: docker exec -t dev_rucio_1 pytest -v --full-trace lib/rucio/tests/test_rucio_server.py
#      - name: Test Protocol XrootD
#        run: docker exec -t dev_rucio_1 pytest -v --full-trace lib/rucio/tests/test_rse_protocol_xrootd.py
#      - name: Stop containers
#        run: docker-compose -f etc/docker/dev/docker-compose-storage.yml down