name: End to End integration tests

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update pip
        run: python3 -m pip install -U pip setuptools
      - name: Install python requirements for matrix_parser.py
        run: python3 -m pip install -U PyYAML
      - name: Identify Matrix
        id: matrix
        run: echo "::set-output name=matrix::$(jq '.[]  | select(.SUITE=="integration-test")' <<< $(./tools/test/matrix_parser.py < ./etc/docker/test/matrix.yml))"
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}

  integration-tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout rucio containers repository
        uses: actions/checkout@v2
        with:
          repository: rucio/containers
      - uses: actions/checkout@v2
        name: Checkout rucio source
        with:
          path: dev/rucio
      - name: Prepare Images
        shell: bash
        run: |
          sed -i "s/RUN git clone .*/COPY .\/rucio \/tmp\/rucio/" $GITHUB_WORKSPACE/dev/Dockerfile_py3
      - name: Build Images
        uses: whoan/docker-build-with-cache-action@v5
        id: build
        with:
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
          registry: docker.pkg.github.com
          context: "${{ github.workspace }}/dev"
          dockerfile: Dockerfile_py3
          image_name: rucio-dev
      - name: Prepare Docker Compose
        shell: bash
        run: |
          IMG=$(echo "${{ steps.build.outputs.FULL_IMAGE_NAME }}" | sed 's_/_\\/_g')
          sed "s/image: rucio\/rucio-dev/image: $IMG/" $GITHUB_WORKSPACE/dev/rucio/etc/docker/dev/docker-compose-storage.yml
      - name: Start containers
        run: docker-compose -f $GITHUB_WORKSPACE/dev/rucio/etc/docker/dev/docker-compose-storage.yml up -d
      - name: Initialize tests
        shell: bash
        run: |
          docker exec -t dev_rucio_1 cp etc/rse-accounts.cfg.template etc/rse-accounts.cfg
          docker exec -t dev_rucio_1 tools/run_tests_docker.sh -ir
      - name: File Upload/Download Test
        run: docker exec -t dev_rucio_1 pytest -v --full-trace lib/rucio/tests/test_rucio_server.py
      - name: Test Protocol XrootD
        run: docker exec -t dev_rucio_1 pytest -v --full-trace lib/rucio/tests/test_rse_protocol_xrootd.py
      - name: Stop containers
        run: docker-compose -f $GITHUB_WORKSPACE/dev/rucio/etc/docker/dev/docker-compose-storage.yml down
    outputs:
      image: ${{ steps.build.outputs.FULL_IMAGE_NAME }}