name: Run upload/download tests with XrootD containers

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start containers
      run: docker-compose -f etc/docker/dev/docker-compose-storage.yml up -d
    - name: Execute tests
      run: docker exec -it dev_rucio_1 tools/run_tests_docker.sh -ir