name: Run upload/download tests with XrootD containers

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  runs-on: 'ubuntu-latest'
  steps:
    - uses: actions/checkout@v2
    - name: Start containers
      run: docker-compose -f etc/docker/dev/docker-compose-storage.yml up -d